# Generated by Django 4.2.2 on 2023-06-21 11:50

import autoslug.fields
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=main.models.slugify_fun, unique=True),
        ),
    ]
